### PR TITLE
Feature final sections

### PR DESCRIPTION
**Pull request by kalavhan**
Second pull request for review

### CODE REVIEW

**Comment by shloch** [comment]
### Changes Required 🤓
Hi @Fig77  and @kalavhan  👋,

You've done a great job setting up this project so far. I like the design 😄

There're just TWO (02) tasks left :

- Validate your HTML markup (you can use --> https://validator.w3.org/ ), its almost valid, few things left out. Please check it out

- Configure stickler on this project and validate all stickler-related errors (if there's any)

```
**Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you.**
```

Happy coding 😄,
--SHEY**_

**Comment by Fig77** [comment]
closing pull request to make another one for review

**Comment by shloch** [comment]
No, please ask for review with this same PULL REQUEST link

**Comment by Fig77** [comment]
> 
> 
> No, please ask for review with this same PULL REQUEST link

Oh sorry! we already did it the other way. Because members of my team told me I should do it like that. What should we do about it?

**Pull request closed without merging**
